@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
!pragma layout smetana

class Webserver {
- {static} PORT :int
- {static} FORMATTER : DateTimeFormatter
+ Webserver()
}

class SocketThread {
- insocked : Socked
- makeRequest(tokens : String[]) : Request
- makeRequestReader(tokens : String[]) : RequestReader
- makeRequestArea(tokens : String[]) : RequestArea
- makeHeaderAnswer() : String
- makeJsonAnswer(request : Request) : String
+ run()
}

Webserver +-right- SocketThread

note right of SocketThread
inner class
of Webserver
end note

class DirectoryAreas
{
{static}-rootArea: Area
{static}-allDoors: Door[]
{static}+makeAreas()
{static}+findAreaById(id : String) : Area
{static}-findDoorsByIds(ids : String[]) : Door[]
{static}+findDoorById(id : String) : Door
{static}+getAllDoors() : Door[]
}

DirectoryAreas --> "*" Area : "rootArea"

class Door {
- id : String
- closed : boolean
- currentState : DoorState
+ Door(id : String, Space : fromSpace, Space : toSpace)
+ processRequest(request : RequestReader)
+ toJson() : JSONObject

'+ toString() : String
'+ isClosed() :boolean
'+ setClosed(b : boolean)
'+ getStateName() : String

}

class DirectoryUserGroups {
- userGroups : UserGroup[]
+ makeUserGroups()
+ findUserByCredential(credential : String) : User
}

DirectoryUserGroups o--> "1..*" UserGroup : "userGroups"
UserGroup "1 userGroup"*-->"users*" User

class UserGroup {
- users : User
- allowedActions : String[]
- allowedAreas : String[]
- schedule : Schedule
+ addUser(user : User)
+ canSendRequests() : Boolean
+ canBeInSpace() : Boolean
+ canDoAction() : Boolean
}

UserGroup -right->"1" Schedule

class Schedule {
- weekDays : DayOfWeek[]
- startTime : LocalTime
- endTime : LocalTime
- startDate : LocalDate
- endDate : LocalDate

+ Schedule(weekDays : DayOfWeek[], startTime : LocalTime, endTime : LocalTime
    startDate : LocalDate, endDate : LocalDate)
+ isAllowedAt(dateTime : LocalDateTime)
}

class User {
- name : String
- credential : String
- userGroup : UserGroup
+ User(name: String, credential: String)
+ toString() : String
}


class Main {
+ {static} main(args : String)
}

abstract DoorState{
# door : Door
# name : String
{abstract}+ open()
{abstract}+ close()
{abstract}+ lock()
{abstract}+ unlock()
{abstract}+ unlockShortly()
{abstract}+ prop()
}

class Locked extends DoorState{
+ open()
+ close()
+ lock()
+ unlock()
+ unlockShortly()
+ prop()
}

class Unlocked extends DoorState{
+ open()
+ close()
+ lock()
+ unlock()
+ unlockShortly()
+ prop()
}

class UnlockedShortly extends DoorState{
+ open()
+ close()
+ lock()
+ unlock()
+ unlockShortly()
+ prop()
}

class Propped extends DoorState{
+ open()
+ close()
+ lock()
+ unlock()
+ unlockShortly()
+ prop()
}

abstract Area{
#id : String
#name : String
#parent: Area
{abstract}+ getSpaces() : Space[]
{abstract}+ getDoorsGivingAccess() : Door[]
{abstract}+ findAreaById(id : String) : Area
}

class Space extends Area{
- doors : Door[]
+ getSpaces() : Space[]
+ getDoorsGivingAccess() : Door[]
+ findAreaById(id : String) : Area
}

class Partition extends Area{
- areas : Area[]
+ getSpaces() : Space[]
+ getDoorsGivingAccess() : Door[]
+ findAreaById(id : String) : Area
}

note right of Main::main
DirectoryDoors.makeDoors()
DiretoryUsers.makeUsers()
new Webserver()
end note

Main -[hidden]down- Webserver
Webserver -[hidden]down- DirectoryDoors
DirectoryDoors -[hidden]right- DirectoryUserGroups
Door -->"1" DoorState : currentState
Partition *-->"*" Area : areas
Space -->"*" Door : doors
@enduml
